%% Orientation column
%
%
% YC at ES lab
% Created on Sep. 1, 2021
% Last modified on Sep. 21, 2021

%% Clear workspace
clearvars;
close all;

%% Timer starts
TimerStart = now;
disp(['Session starts at ',datestr(TimerStart)]);

%% General parameters
DefaultValues;

%% Experiment list
fnRoot = 'M28D20210816R1';

%% Paramters
iCondBlank = 1;
iCond0 = 2;
iCond90 = 3;

AmpThsd = 0.01;

%% Load data
load(['Data/',fnRoot,'TS.mat'],'TS');
load(['Data/',fnRoot,'FFTAmpS014E113PF0400.mat'],'DataCond','DataTrial');

%% Filter
DataCondLow = ...
  FilterFermi2D(DataCond,0,0.8,TS.Header.Imaging.SizePxl);  % low pass to get ROI
DataCondBand = ...
  FilterFermi2D(DataCond,0.8,3,TS.Header.Imaging.SizePxl);  % band-pass to get columns
DataTrialBand = ...
  FilterFermi2D(DataTrial,0.8,3,TS.Header.Imaging.SizePxl);  % band-pass to get columns

%% Remove blank
DataCondLow = DataCondLow-repmat(DataCondLow(:,:,iCondBlank),[1,1,3]);
DataCondBand = DataCondBand-repmat(DataCondBand(:,:,iCondBlank),[1,1,3]);
DataTrialBand = ...
  DataTrialBand- ...
  repmat(DataCondBand(:,:,iCondBlank),[1,1,size(DataTrialBand,3)]);

%% Make a mask based on the amplitude
MaskROI = ...
  mean(DataCondLow(:,:,[iCond0,iCond90]),3)>AmpThsd;

%% Orientation column
OrtCol = DataCondBand(:,:,iCond0)-DataCondBand(:,:,iCond90);

%% Correlation with ROI
tDataCondBand0 = DataCondBand(:,:,iCond0);
tDataCondBand90 = DataCondBand(:,:,iCond90);
t = corrcoef(tDataCondBand0(MaskROI),tDataCondBand90(MaskROI));
CorrOrt = t(1,2);

%% Discrimination
[DP,DPBSSE,Weight,vA,vB] = ...
  CalculateDiscrimination( ...
    DataTrialBand(:,:,TS.Header.Index.iValidBLKCond{iCond0}), ...
    DataTrialBand(:,:,TS.Header.Index.iValidBLKCond{iCond90}));
sParm.Mask=MaskROI;
[DPMask,DPBSSEMask,WeightMask,vAMask,vBMask] = ...
  CalculateDiscrimination( ...
    DataTrialBand(:,:,TS.Header.Index.iValidBLKCond{iCond0}), ...
    DataTrialBand(:,:,TS.Header.Index.iValidBLKCond{iCond90}),sParm);

%% Figure
disp('Creating figures ...');

CLimLow = [min(DataCondLow(:)),max(DataCondLow(:))];
CLimBand = [min(DataCondBand(:)),max(DataCondBand(:))];

hgfFig = figure;
annotation('TextBox',[0.05,0.7,0.9,0.1], ...
           'String','Orientation columns', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',18, ...
           'LineStyle','None');
annotation('TextBox',[0.05,0.5,0.9,0.1], ...
           'String',fnRoot, ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',16, ...
           'LineStyle','None');
annotation('TextBox',[0.05,0.3,0.9,0.1], ...
           'String','Yuzhi Chen', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',16, ...
           'LineStyle','None');
annotation('TextBox',[0.05,0.2,0.9,0.1], ...
           'String',date, ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',14, ...
           'LineStyle','None');

hgfFig(end+1) = figure;
annotation('TextBox',[0,0.9,1,0.1], ...
           'String', ...
           'Raw 4Hz amplitude response maps', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',12, ...
           'LineStyle','None');
axes('Position',[0.05,0.2,0.42,0.56]);
imagesc(DataCond(:,:,iCond0),CLimLow);
axis image off;
title('Orientation 0^o', ...
      'FontSize',12, ...
      'FontWeight','Bold');
axes('Position',[0.5,0.2,0.42,0.56]);
imagesc(DataCond(:,:,iCond90),CLimLow);
axis image off;
title('Orientation 90^o', ...
      'FontSize',12, ...
      'FontWeight','Bold');
th = colorbar;
tPos = get(th,'Position');
set(th,'Position',[0.93,0.2,tPos(3:4)]);

hgfFig(end+1) = figure;
annotation('TextBox',[0,0.9,1,0.1], ...
           'String', ...
           'Low-pass filter (0~0.8cpmm) for ROI', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',12, ...
           'LineStyle','None');
axes('Position',[0.05,0.2,0.42,0.56]);
imagesc(DataCondLow(:,:,iCond0),CLimLow);
axis image off;
title('Orientation 0^o', ...
      'FontSize',12, ...
      'FontWeight','Bold');
axes('Position',[0.5,0.2,0.42,0.56]);
imagesc(DataCondLow(:,:,iCond90),CLimLow);
axis image off;
title('Orientation 90^o', ...
      'FontSize',12, ...
      'FontWeight','Bold');
th = colorbar;
tPos = get(th,'Position');
set(th,'Position',[0.93,0.2,tPos(3:4)]);

hgfFig(end+1) = figure;
annotation('TextBox',[0,0.9,1,0.1], ...
           'String', ...
           'ROI---mean of low-pass 0^o and 90^o > threshould (0.01)', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',12, ...
           'LineStyle','None');
axes('Position',[0.26,0.2,0.42,0.56]);
imagesc(MaskROI);
axis image off;

hgfFig(end+1) = figure;
annotation('TextBox',[0,0.9,1,0.1], ...
           'String', ...
           'Band-pass filter (0.8~3cpmm) for orientation columns', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',12, ...
           'LineStyle','None');
axes('Position',[0.05,0.2,0.42,0.56]);
imagesc(DataCondBand(:,:,iCond0),CLimBand);
axis image off;
title('Orientation 0^o', ...
      'FontSize',12, ...
      'FontWeight','Bold');
axes('Position',[0.5,0.2,0.42,0.56]);
imagesc(DataCondBand(:,:,iCond90),CLimBand);
axis image off;
title('Orientation 90^o', ...
      'FontSize',12, ...
      'FontWeight','Bold');
th = colorbar;
tPos = get(th,'Position');
set(th,'Position',[0.93,0.2,tPos(3:4)]);

hgfFig(end+1) = figure;
annotation('TextBox',[0,0.9,1,0.1], ...
           'String', ...
           'Orientation columns (band-pass 0^o - 90^o)', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',12, ...
           'LineStyle','None');
axes('Position',[0.26,0.2,0.42,0.56]);
imagesc(OrtCol);
axis image off;
th = colorbar;
tPos = get(th,'Position');
set(th,'Position',[0.7,0.2,tPos(3:4)]);

hgfFig(end+1) = figure;
annotation('TextBox',[0,0.9,1,0.1], ...
           'String', ...
           'Orientation columns (band-pass 0^o - 90^o) within ROI', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',12, ...
           'LineStyle','None');
axes('Position',[0.26,0.2,0.42,0.56]);
tData = OrtCol;
tData(~MaskROI) = NaN;
imagesc(tData);
axis image off;
th = colorbar;
tPos = get(th,'Position');
set(th,'Position',[0.7,0.2,tPos(3:4)]);

hgfFig(end+1) = figure;
annotation('TextBox',[0,0.9,1,0.1], ...
           'String', ...
           'Orientation discrimination (band-pass)', ...
           'HorizontalAlignment','Center', ...
           'FontWeight','bold', ...
           'FontSize',12, ...
           'LineStyle','None');
axes('Position',[0.1,0.3,0.3,0.4]);
vEdge = linspace(min(min(vA),min(vB)),max(max(vA),max(vB)),13);
HistA = histcounts(vA,vEdge);
HistB = histcounts(vB,vEdge);
vHist = vEdge(1:end-1)+(vEdge(2)-vEdge(1))/2;
bar(vEdge(1:end-1)+(vEdge(2)-vEdge(1))/4,HistA,0.5, ...
    'EdgeColor','r', ...
    'FaceColor','r');
hold on;
bar(vEdge(1:end-1)-(vEdge(2)-vEdge(1))/4,HistB,0.5, ...
    'EdgeColor','b', ...
    'FaceColor','b');
hold off;
xlabel('Decision variable', ...
       'FontSize',12, ...
       'FontWeight','Bold');
ylabel('Trial counts', ...
       'FontSize',12, ...
       'FontWeight','Bold');
title(sprintf('without mask\nd''=%0.2f',DP), ...
      'FontSize',12, ...
      'FontWeight','Bold');
axes('Position',[0.55,0.3,0.3,0.4]);
vEdge = linspace(min(min(vAMask),min(vBMask)),max(max(vAMask),max(vBMask)),13);
HistA = histcounts(vAMask,vEdge);
HistB = histcounts(vBMask,vEdge);
vHist = vEdge(1:end-1)+(vEdge(2)-vEdge(1))/2;
bar(vEdge(1:end-1)+(vEdge(2)-vEdge(1))/4,HistA,0.5, ...
    'EdgeColor','r', ...
    'FaceColor','r');
hold on;
bar(vEdge(1:end-1)-(vEdge(2)-vEdge(1))/4,HistB,0.5, ...
    'EdgeColor','b', ...
    'FaceColor','b');
hold off;
xlabel('Decision variable', ...
       'FontSize',12, ...
       'FontWeight','Bold');
ylabel('Trial counts', ...
       'FontSize',12, ...
       'FontWeight','Bold');
title(sprintf('with mask\nd''=%0.2f',DPMask), ...
      'FontSize',12, ...
      'FontWeight','Bold');

%% Save figures to pdf
fnFig = fullfile('Figures',[fnRoot,'OrtCul20210901_gen.pdf']);
SavePDF(hgfFig,fnFig);

%% Timer ends
TimerEnd = now;
disp(['Session started at ',datestr(TimerStart)]);
disp(['Session ended at ',datestr(TimerEnd)]);


